version: '3.0'
services:
  exam-api:
    container_name: exam-api
    build: ./docker
    image: abobby/php-apache
    ports:
      - '8080:80'
    volumes:
      - ".:/var/www/html"
      - "./docker/config/vhost.conf:/etc/apache2/site-available/000-default.conf"
    depends_on:
      - mysqldb
    restart:
      on-failure
  mysqldb:
   image: percona:latest
   ports:
     - '3310:3306'
   environment:
      MYSQL_DATABASE: webdb
      MYSQL_PASSWORD: secret
      MYSQL_USER: dbuser
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
   volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
    driver: local